### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by mnordseth** [sweeto/app#1]
Running 
  client.py --replay-data=status_dumps/sofa.json
causes the app to crash :/

<img width="1874" alt="screen shot 2015-11-11 at 22 17 39" src="https://cloud.githubusercontent.com/assets/2326316/11103372/56a7357c-88c2-11e5-9d3d-02df2338d24f.png">

**Comment by mikberg** [comment]
Are all the messages in JSON format?
